INTYGFV-1196: använd bas-images från nexus istället för is (pga strul med rättigheter i OCP)

diff --git a/devops/openshift/pipelinetemplate-build-webapp.yaml b/devops/openshift/pipelinetemplate-build-webapp.yaml
--- a/devops/openshift/pipelinetemplate-build-webapp.yaml
+++ b/devops/openshift/pipelinetemplate-build-webapp.yaml
@@ -22,12 +22,6 @@ parameters:
     value: "artifact"
   - name: GIT_URL
     required: true
-  - name: TESTS
-    value: "-"
-    required: true
-  - name: BACKING_SERVICES
-    value: "-"
-    required: true
   - name: TEST_PORT
     value: "8080"
     required: true
@@ -76,10 +70,11 @@ objects:
             def commonVersion = "NA"
             def infraVersion = "NA"
             def releaseBuild = GIT_BRANCH.startsWith("release")
-            def backingServices = "${BACKING_SERVICES}"
+            def backingService = ""
             def artifactFolder = "target"
             def applicationZip = "${artifactFolder}/${APP_NAME}-${BUILD_NUMBER}.tar.gz"
             def versionFlags = ""
+            def tests = []
             def buildArgs = "clean build"
             def uploadArchives = false
 
@@ -225,14 +220,17 @@ objects:
                       if (info.infraVersion) {
                         infraVersion = info.infraVersion
                       }
-                      if (info.backingServices) {
-                        backingServices = info.backingServices
+                      if (info.backingService) {
+                        backingService = info.backingService
                       }
                       if (info.buildArgs) {
                         buildArgs = info.buildArgs
                       }
                       if (info.uploadArchives) {
                         uploadArchives = info.uploadArchives
+                      }
+                      if (info.tests) {
+                        tests = info.tests
                       }
                       versionFlags = "-DbuildVersion=${buildVersion} -DcommonVersion=${commonVersion} -DinfraVersion=${infraVersion}"
                     }
@@ -254,7 +252,7 @@ objects:
                           echo "release: ${releaseBuild}"
                           echo "gitUrl: ${gitUrl}, gitBranch: ${GIT_BRANCH}"
                           echo "buildVersion: ${buildVersion}, infraVersion: ${infraVersion}, commonVersion: ${commonVersion}"
-                          echo "backingServices: ${backingServices}"
+                          echo "backingService: ${backingService}"
 
                           // check envrionment
                           [ gitUrl, GIT_BRANCH, buildVersion ].each {
@@ -416,85 +414,80 @@ objects:
               stage('Deploy Intygstjänst') {
                   when {
                       expression {
-                        if (backingServices == "-") {
-                          return false
-                        }
-                        return true
+                        return !backingService.empty
                       }
                   }
                   steps {
                       script {
                           openshift.withCluster() {
                               openshift.withProject() {
-                                  backingServices.split(",").each {
-                                      // [ name, tag ] default version is latest
-                                      def svc = (it.contains(":") ? it : it + ":latest").split(":")
+                                  // [ name, tag ] default version is latest
+                                  def svc = (backingService.contains(":") ? backingService : backingService + ":latest").split(":")
 
-                                      def imageStream = openshift.selector("is", "${svc[0]}-verified").object().status.dockerImageRepository
-                                      echo "Use ImageStream ${imageStream}:${svc[1]}"
-                                      def healthUri = "/"
-                                      // FIXME: dirty work-around!
-                                      if (svc[0].startsWith("intygstjanst")) {
-                                        healthUri += "inera-certificate"
-                                      } else {
-                                        error("For the time being, intygstjanst only is allowed as a backing service")
-                                      }
-                                      def backDbName = "${svc[0].replace('-', '')}${dbName}"
-                                      def status = dbScript("create database ${backDbName} character set utf8mb4;")
-                                      if (status != 0) {
-                                          error("Unable to create database ${backDbName}")
-                                      }
+                                  def imageStream = openshift.selector("is", "${svc[0]}-verified").object().status.dockerImageRepository
+                                  echo "Use ImageStream ${imageStream}:${svc[1]}"
+                                  def healthUri = "/"
+                                  // FIXME: dirty work-around!
+                                  if (svc[0].startsWith("intygstjanst")) {
+                                    healthUri += "inera-certificate"
+                                  } else {
+                                    error("For the time being, intygstjanst only is allowed as a backing service")
+                                  }
+                                  def backDbName = "${svc[0].replace('-', '')}${dbName}"
+                                  def status = dbScript("create database ${backDbName} character set utf8mb4;")
+                                  if (status != 0) {
+                                      error("Unable to create database ${backDbName}")
+                                  }
 
-                                      // checkout actual configuration for the base service version, then copy to the actual backing service name.
-                                      // Note: not multi-thread safe, implies one build at a time
-                                      def svcAppName = "${svc[0]}-${APP_NAME}"
-                                      def svcGitRef = svc[1].equals("latest") ? "develop" : "tags/v${svc[1]}"
+                                  // checkout actual configuration for the base service version, then copy to the actual backing service name.
+                                  // Note: not multi-thread safe, implies one build at a time
+                                  def svcAppName = "${svc[0]}-${APP_NAME}"
+                                  def svcGitRef = svc[1].equals("latest") ? "develop" : "tags/v${svc[1]}"
 
-                                      echo "Extract config for intygstjanst ${svcGitRef}"
+                                  echo "Extract config for intygstjanst ${svcGitRef}"
 
-                                      extractConfig(tmpDir, "https://github.com/sklintyg/intygstjanst.git", svcGitRef, "${STAGE}")
+                                  extractConfig(tmpDir, "https://github.com/sklintyg/intygstjanst.git", svcGitRef, "${STAGE}")
 
-                                      shell("oc delete configmap ${svc[0]}-config")
-                                      shell("oc delete secret ${svc[0]}-env")
-                                      shell("oc delete configmap ${svc[0]}-configmap-envvar")
-                                      
-                                      // TODO: Finalize handling of secret vars
-                                      // shell("[ -f ${STAGE}/secret-vars.yaml ] && oc delete secret ${APP_NAME}-secret-envvar || true")
-                                      
-                                      def wd = "cd ${tmpDir}/devops/openshift; "
-                                      eshell(wd + "[ -f ${STAGE}/configmap-vars.yaml ] && oc create -f ${STAGE}/configmap-vars.yaml || true")
-                                      // eshell(wd + "[ -f ${STAGE}/secret-vars.yaml ] && oc create -f ${STAGE}/secret-vars.yaml || true")
-                                      eshell(wd + "oc create configmap ${svc[0]}-config --from-file=${STAGE}/config/")
-                                      eshell(wd + "oc create secret generic ${svc[0]}-env --from-file=${STAGE}/env/ --type=Opaque")
+                                  shell("oc delete configmap ${svc[0]}-config")
+                                  shell("oc delete secret ${svc[0]}-env")
+                                  shell("oc delete configmap ${svc[0]}-configmap-envvar")
+                                  
+                                  // TODO: Finalize handling of secret vars
+                                  // shell("[ -f ${STAGE}/secret-vars.yaml ] && oc delete secret ${APP_NAME}-secret-envvar || true")
+                                  
+                                  def wd = "cd ${tmpDir}/devops/openshift; "
+                                  eshell(wd + "[ -f ${STAGE}/configmap-vars.yaml ] && oc create -f ${STAGE}/configmap-vars.yaml || true")
+                                  // eshell(wd + "[ -f ${STAGE}/secret-vars.yaml ] && oc create -f ${STAGE}/secret-vars.yaml || true")
+                                  eshell(wd + "oc create configmap ${svc[0]}-config --from-file=${STAGE}/config/")
+                                  eshell(wd + "oc create secret generic ${svc[0]}-env --from-file=${STAGE}/env/ --type=Opaque")
 
-                                      // Configmap for /$STAGE/config
-                                      eshell("oc get configmap ${svc[0]}-config -o yaml --export | sed \'s/name: ${svc[0]}-config/name: ${svcAppName}-config/g\' | oc apply -f -")
+                                  // Configmap for /$STAGE/config
+                                  eshell("oc get configmap ${svc[0]}-config -o yaml --export | sed \'s/name: ${svc[0]}-config/name: ${svcAppName}-config/g\' | oc apply -f -")
 
-                                      // Secret for /$STAGE/env
-                                      eshell("oc get secret ${svc[0]}-env -o yaml --export | sed \'s/name: ${svc[0]}-env/name: ${svcAppName}-env/g\' | oc apply -f -")
+                                  // Secret for /$STAGE/env
+                                  eshell("oc get secret ${svc[0]}-env -o yaml --export | sed \'s/name: ${svc[0]}-env/name: ${svcAppName}-env/g\' | oc apply -f -")
 
-                                      // Certificates /$STAGE/certifikat
-                                      eshell("oc get secret ${svc[0]}-certifikat -o yaml --export | sed \'s/name: ${svc[0]}-certifikat/name: ${svcAppName}-certifikat/g\' | oc apply -f -")
+                                  // Certificates /$STAGE/certifikat
+                                  eshell("oc get secret ${svc[0]}-certifikat -o yaml --export | sed \'s/name: ${svc[0]}-certifikat/name: ${svcAppName}-certifikat/g\' | oc apply -f -")
 
-                                      // Secret for envvars
-                                      eshell("oc get secret ${svc[0]}-secret-envvar -o yaml --export | sed \'s/name: ${svc[0]}-secret-envvar/name: ${svcAppName}-secret-envvar/g\' | oc apply -f -")
+                                  // Secret for envvars
+                                  eshell("oc get secret ${svc[0]}-secret-envvar -o yaml --export | sed \'s/name: ${svc[0]}-secret-envvar/name: ${svcAppName}-secret-envvar/g\' | oc apply -f -")
 
-                                      // Config-map for envvars
-                                      eshell("oc get configmap ${svc[0]}-configmap-envvar -o yaml --export | sed \'s/name: ${svc[0]}-configmap-envvar/name: ${svcAppName}-configmap-envvar/g\' | oc apply -f -")
+                                  // Config-map for envvars
+                                  eshell("oc get configmap ${svc[0]}-configmap-envvar -o yaml --export | sed \'s/name: ${svc[0]}-configmap-envvar/name: ${svcAppName}-configmap-envvar/g\' | oc apply -f -")
 
-                                      def deployModel = openshift.process("deploytemplate-webapp",
-                                              "-p", "APP_NAME=${svcAppName}",
-                                              "-p", "IMAGE='${imageStream}:${svc[1]}'",
-                                              "-p", "DATABASE_NAME=${backDbName}",
-                                              "-p", "HEALTH_URI=${healthUri}",
-                                              "-p", "STAGE=test")
-                                      log "Wait for rollout (limited to 5 minutes)"
-                                      timeout (5) {
-                                          def rm = openshift.apply(deployModel).narrow("dc").rollout()
-                                          echo "Waiting for deployment to complete"
-                                          rm.status()
-                                          log "Deployment done."
-                                      }
+                                  def deployModel = openshift.process("deploytemplate-webapp",
+                                          "-p", "APP_NAME=${svcAppName}",
+                                          "-p", "IMAGE='${imageStream}:${svc[1]}'",
+                                          "-p", "DATABASE_NAME=${backDbName}",
+                                          "-p", "HEALTH_URI=${healthUri}",
+                                          "-p", "STAGE=test")
+                                  log "Wait for rollout (limited to 5 minutes)"
+                                  timeout (5) {
+                                      def rm = openshift.apply(deployModel).narrow("dc").rollout()
+                                      echo "Waiting for deployment to complete"
+                                      rm.status()
+                                      log "Deployment done."
                                   }
                               }
                           }
@@ -533,14 +526,14 @@ objects:
               stage('Run Tests') {
                 when {
                   expression {
-                    return !"${TESTS}".equals("-")
+                    return !tests.empty
                   }                      
                 }
                 steps {
                   script {
                     openshift.withCluster() {
                       openshift.withProject() {
-                        "${TESTS}".split(",").each { t ->
+                        tests.each { t ->
                           stage(t.capitalize()) {
                             performTest(t, buildVersion)
                           }
@@ -660,7 +653,6 @@ objects:
                   openshift.withCluster() {
                     openshift.withProject() {
                       dbScript("drop database ${dbName};")
-
                       echo "Logs for ${APP_NAME}"
                       openshift.selector( "dc", "${APP_NAME}" ).logs()
 
@@ -669,31 +661,29 @@ objects:
                       
                       shell("oc process ${DEPLOY_TEMPLATE} -p APP_NAME=\"${APP_NAME}\" -p IMAGE=\"${imageStream}:${buildVersion}\" -p STAGE=${STAGE} -p DATABASE_NAME=${dbName} | oc delete -f -")
 
-                      if (backingServices != "-") {
-                          backingServices.split(",").each {
-                              def svc = (it.contains(":") ? it : it + ":latest").split(":")
-                              
-                              def svcAppName = "${svc[0]}-${APP_NAME}"
-                              echo "Logs for ${svcAppName}"
-                              openshift.selector( "dc", "${svcAppName}" ).logs()
+                      if (!backingService.empty) {
+                          def svc = (backingService.contains(":") ? backingService : backingService + ":latest").split(":")
+                          
+                          def svcAppName = "${svc[0]}-${APP_NAME}"
+                          echo "Logs for ${svcAppName}"
+                          openshift.selector( "dc", "${svcAppName}" ).logs()
 
-                              imageStream = openshift.selector("is", "${svc[0]}-verified").object().status.dockerImageRepository
-                              def backDbName = "${svc[0].replace('-', '')}${dbName}"
+                          imageStream = openshift.selector("is", "${svc[0]}-verified").object().status.dockerImageRepository
+                          def backDbName = "${svc[0].replace('-', '')}${dbName}"
 
-                              shell("oc process ${DEPLOY_TEMPLATE} -p APP_NAME=\"${svcAppName}\" -p IMAGE=\"${imageStream}:${svc[1]}\" -p STAGE=${STAGE} -p DATABASE_NAME=${backDbName} | oc delete -f -")
-                              dbScript("drop database ${backDbName};")
+                          shell("oc process ${DEPLOY_TEMPLATE} -p APP_NAME=\"${svcAppName}\" -p IMAGE=\"${imageStream}:${svc[1]}\" -p STAGE=${STAGE} -p DATABASE_NAME=${backDbName} | oc delete -f -")
+                          dbScript("drop database ${backDbName};")
 
-                              // Delete /config configmap
-                              shell("oc delete configmap ${svcAppName}-config")
-                              // Delete /env secret
-                              shell("oc delete secret ${svcAppName}-env")          
-                              // Delete /certifikat secret
-                              shell("oc delete secret ${svcAppName}-certifikat")
-                              // Delete configmap envvar
-                              shell("oc delete configmap ${svcAppName}-configmap-envvar")
-                              // Delete secret envvar
-                              shell("oc delete secret ${svcAppName}-secret-envvar")
-                          }
+                          // Delete /config configmap
+                          shell("oc delete configmap ${svcAppName}-config")
+                          // Delete /env secret
+                          shell("oc delete secret ${svcAppName}-env")          
+                          // Delete /certifikat secret
+                          shell("oc delete secret ${svcAppName}-certifikat")
+                          // Delete configmap envvar
+                          shell("oc delete configmap ${svcAppName}-configmap-envvar")
+                          // Delete secret envvar
+                          shell("oc delete secret ${svcAppName}-secret-envvar")
                         }
                       }
                     }
